# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

:trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  jobs:
  - job: Terraform_Deploy
    steps:

    # Install Terraform
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    # Init
    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    # Validate
    - task: TerraformTaskV4@4
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    # Plan
    - task: TerraformTaskV4@4
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: '<your-service-connection>'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    # Apply
    - task: TerraformTaskV4@4
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: '<your-service-connection>'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

